### ISSUE TITLE
Bug: when trying to delete or complete.

### ISSUE THREAD

**Issue by JuanRojasAguilar** [paranoidbarbie/youtube#1]
Hi, love your vids!

The issue is in **c/taskApp**
I noticed that we are using choice variable to send the index of the task we want to delete we can also send 4 as an index and the app will exit.

I created idxChoice as an int to unbind the same choice variable we use to navigate through the switch.

Here's an img.

<img width="415" alt="Screenshot 2024-07-16 at 18 27 17" src="https://github.com/user-attachments/assets/1f2256d3-01aa-4606-be3f-64b74218e621">

**Comment by paranoidbarbie** [comment]
Thanks for pointing it out, it should be fixed now, would be grateful if you test and reply. In wait for your reply. Thanks.

**Comment by JuanRojasAguilar** [comment]
It really does work!
That's a clever way of avoiding having to create a new int variable.
